services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        networks:
            - mongodb_network
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: supersecret
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        ports:
            - "8081:8081"
        networks:
            - mongodb_network
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: supersecret
